ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ br.com.trabalhoarretado.ApplicationKt.module ]
    }
}

database {
    url = ${DATABASE_URL}
    user = ${DATABASE_USER}
    password = ${DATABASE_PASSWORD}
}

jwt {
    secret = ${JWT_SECRET}
    issuer = "trabalho-arretado"
    audience = "trabalho-arretado-users"
    realm = "Trabalho Arretado"
    expiresInDays = 7
}

s3 {
    endpoint = ${S3_ENDPOINT}
    region = ${S3_REGION}
    accessKey = ${S3_ACCESS_KEY}
    secretKey = ${S3_SECRET_KEY}
    bucket = ${S3_BUCKET}
    publicBaseUrl = ${S3_PUBLIC_BASE_URL}
    pathStyle = true
    pathStyle = ${?S3_PATH_STYLE}
}
